server:
 port: 8081
spring:
 application:
  name: spring-boot-with-aws-ecs-s3-event-bridge
employee:
 name: ramireddy

read:
 env:
  value:
    from:
     ecs:
      task: ${BUCKET_NAME:poc-ved-bucket-s3}
